# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SGBTools
                                 A QGIS plugin
 Ferramentas SGB
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-30
        copyright            : (C) 2024 by Carlos Eduardo Mota
        email                : carlos.mota@sgb.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Carlos Eduardo Mota'
__date__ = '2024-10-30'
__copyright__ = '(C) 2024 by Carlos Eduardo Mota'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessingParameterMapLayer,
                       QgsProcessingParameterMultipleLayers,
                       QgsProcessingOutputBoolean,
                       QgsProcessingParameterBoolean,
                       QgsRectangle,
                       QgsLayerMetadata,
                       QgsAbstractMetadataBase,
                       QgsProcessingParameterDefinition)
from owslib import iso, etree
#owslib is spitting a lot of future change warnings those will be ignored
#for now
import warnings
warnings.filterwarnings('ignore', module='owslib')

from .import_iso_metadata import createSpatialExtent


class CopyMetadataAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    INPUTMAPLAYER = 'INPUTMAPLAYER'
    OUTPUTMAPLAYERLIST = 'OUTPUTMAPLAYERLIST'
    OUTPUT = 'OUTPUT'

    COPYEXTENT = 'COPYEXTENT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.addParameter(
            QgsProcessingParameterMapLayer(
                self.INPUTMAPLAYER,
                self.tr('Layer to copy from')
            )
        )

        layerlist_parameter = QgsProcessingParameterMultipleLayers(
                self.OUTPUTMAPLAYERLIST,
                self.tr('Layers to copy to')
            )
        layerlist_parameter.setMinimumNumberInputs(1)
        self.addParameter(layerlist_parameter)

        extent_parameter = QgsProcessingParameterBoolean(
                self.COPYEXTENT,
                self.tr('Copy extent from metadata'),
                defaultValue=False,
            )
        extent_parameter.setFlags(QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(extent_parameter)

        self.addOutput(
            QgsProcessingOutputBoolean(
                self.OUTPUT,
                self.tr('Return code')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """      
        input_layer = self.parameterAsLayer(parameters, self.INPUTMAPLAYER, context)
        metadata = input_layer.metadata()
        output_layer_list = self.parameterAsLayerList(parameters,self.OUTPUTMAPLAYERLIST,context)
        for layer in output_layer_list:
            new_metadata = metadata
            if not self.parameterAsBoolean(parameters,self.COPYEXTENT,context):
                bbox_rect = layer.extent()
                bbox_crs = layer.crs()
                md_extent = createSpatialExtent(bbox_rect,bbox_crs)
                new_metadata.setExtent(md_extent)
            layer.setMetadata(new_metadata)

        feedback.setProgress(int(100))
        return {self.OUTPUT: True}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Copiar Metadados'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Utils'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CopyMetadataAlgorithm()
